Skip to content
DEV Community ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’»
Search...

Log in
Create account

3
Like
3
Unicorn
0
Save

Cover image for Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github ğŸ
Henrique Lopes
Henrique Lopes
Posted on Jan 4

Como adicionar o Snake Game (jogo da cobrinha) no seu perfil do Github ğŸ
#
github
Primeiramente devo deixar claro que esse artigo foi desenvolvido com base em vÃ¡rios outros artigos e reconstruÃ­do para deixar o mais claro possÃ­vel a forma para inserir o Snake Game em seu perfil.

Funcionamento. "Contributions in the last year":
Basicamente o Snake game funciona realizando uma coleta da sua tabela de contribuiÃ§Ãµes no Github. ele faz a renderizaÃ§Ã£o dessas informaÃ§Ãµes e gera dois arquivos, um em formato gif e outro em svg. SÃ£o esses arquivos que iremos utilizar para inserir a animaÃ§Ã£o no perfil do Github.

Repositorio do projeto a ser utilizado: Platane/snk

Exemple

Requisito. "RepositÃ³rio base":
Para que vocÃª possa prosseguir Ã© necessÃ¡rio que vocÃª tenha o repositÃ³rio do perfil (repositÃ³rio com o mesmo nome de usuÃ¡rio), porÃ©m para gerar os arquivos tambÃ©m funciona em outro repositÃ³rio.

Actions. "ConfiguraÃ§Ã£o inicial":
Inicialmente Ã© necessÃ¡rio que vocÃª acesse o seu repositÃ³rio escolhido e vÃ¡ em Settings.

ConfiguraÃ§Ã£o inicial

No menu vertical ao lado esquerdo selecione o menu Actions e em seguida ative a permissÃ£o â€œAllow all actionsâ€. TambÃ©m Ã© possÃ­vel selecionar diretamente o repositÃ³rio.

Ative a permissÃ£o

Actions. "Criando Gerador":
Agora que temos o repositÃ³rio configurado iremos adicionar o "script" para gerar dos arquivos. No repositÃ³rio, vÃ¡ em Actions.

Criando o gerador

Em seguida vamos utilizar â€œSimple workflowâ€ apenas com o mÃ­nimo necessÃ¡rio para rodar o codigo.

Configurando

Agora Ã© apenas alterar o nome do arquivo e colar o cÃ³digo da configuraÃ§Ã£o com o seu usuÃ¡rio.

Alterar jnome do arquivo

alterando o username
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualizaÃ§Ã£o dos arquivos.
on:
  schedule:
      # SerÃ¡ atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que serÃ¡ utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizaÃ§Ãµes.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Retornando na opÃ§Ã£o Actions do repositÃ³rio, clique em â€œRun workflowâ€:

Repositorio

Pasta dos arquivos:
Em seu repositorio cliente em main e selecione a branch output:
output

E aqui estÃ£o os arquivos gerados que vocÃª pode utilizar como bem entender:

Arquivos

Codigo Github para utilizaÃ§Ã£o:

![snake gif](https://github.com/SEU_USUARIO/SEU_REPOSITORIO/blob/output/github-contribution-grid-snake.svg)

Discussion (0)
Subscribe
pic
Add to the discussion
Code of Conduct â€¢ Report abuse
ğŸŒ± DEV runs on 100% open source code known as Forem.
 
Contribute to the codebase or learn how to host your own.

Read next
balastrong profile image
[Video] How Open Source can change your life
Leonardo Montini - Jul 30

orliesaurus profile image
Just released an open source Stripe App
orliesaurus - Jul 18

mbarzeev profile image
Build Just What You Need
Matti Bar-Zeev - Jul 29

aartiyadav profile image
What is Git?
Aarti Yadav - Jul 18


Henrique Lopes
Follow
"NÃ£o hÃ¡ razÃ£o alguma em usar a palavra â€œimpossÃ­velâ€ para descrever algo que claramente pode acontecer."
JOINED
Sep 5, 2021
Trending on DEV Community ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’» 
Michael Tharrington profile image
What was your win this week?
#discuss #weeklyretro
Patrick Wendo profile image
What if we had a site where you are required to solve duplicated production bugs that other developers have faced?
#discuss #watercooler
Milk profile image
I made the best Github ReadMe EVER!
#github #html #css #webdev
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualizaÃ§Ã£o dos arquivos.
on:
  schedule:
      # SerÃ¡ atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que serÃ¡ utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nomeUsuario #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizaÃ§Ãµes.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
DEV Community ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’» â€” A constructive and inclusive social network for software developers. With you every step of your journey.

Built on Forem â€” the open source software that powers DEV and other inclusive communities.

Made with love and Ruby on Rails. DEV Community ğŸ‘©â€ğŸ’»ğŸ‘¨â€ğŸ’» Â© 2016 - 2022.
